# Generated by Django 4.0.6 on 2022-07-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogology_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='customers',
            new_name='customer',
        ),
    ]
